# Generated by Django 5.2.1 on 2025-06-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferremas', '0003_alter_precioproducto_fecha_alter_producto_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('cliente', 'Cliente')], default='cliente', max_length=10),
        ),
    ]
