# Generated by Django 5.2.1 on 2025-06-02 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ferremas', '0004_usuario_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='rol',
        ),
    ]
